# Day 4

## Exception Handling

In [4]:
try:
    s=5/0
    print(s)
except:
    print("Error")
print("Out")

Error
Out


In [5]:
!pip install numpy

## Using Numpy

In [6]:
import numpy as np

In [10]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [16]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.random.randint(0,100,3)

array([24,  1, 88])

In [70]:
ar=np.array([1,2,3,4,5,6])

In [77]:
ar1=ar.reshape(3,2)
print(ar1)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
max(ar)

6

In [74]:
np.argmax(ar)

5

In [75]:
np.argmin(ar)

0

In [76]:
ar2=ar1[0,1]
print(ar2)

2


In [79]:
ar3=np.array([10,20,30,40,50,60])
print([ar3<50])
print(ar3[ar3<50])

[array([ True,  True,  True,  True, False, False])]
[10 20 30 40]


In [81]:
np.add(ar1,ar1)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])